version: 2
jobs:
  build:
    docker:
      - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.23.2-0
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate docker
          command: |
            docker login -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD" quay.io
      - run:
          name: Pull images (if available)
          command: |
            ./script/pull_dockers.sh || exit 0
      - run:
          name: Build images
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose build
      - run:
          name: Push images
          command: |
            ./script/push_dockers.sh
